FROM python:alpine
LABEL version="1.0.1"
WORKDIR /test/rpsgame-py/python
COPY . /test/rpsgame-py/python/
CMD [ "python" , "RockPaperScissorsGame.py"]

#docker build -t py-game-build .
#docker run -t py-game-build